# fly.toml app configuration file generated for financeapp-29 on 2023-05-14T14:09:06+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "financeapp-29"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
